project:
  type: website

website:
  title: "My Portfolio"
  navbar:
    left:
       - text: "ğŸ  Home"
         href: index1.qmd
       - text: "ğŸ“„ Resume"
         href: resume.qmd
       - text: "ğŸ’¡ Projects"
         href: projects.qmd
       - text: "ğŸ“ Certifications"
         href: certifications.qmd
       - text: "ğŸ“« Contact Me"
         href: contact.qmd

format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css
    toc: true



